version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: salary_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Minfy@Durgesh
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
