artifact_location: file:///C:/Users/Minfy/Desktop/CAPSTONE/your_mlflow_tracking_uri_here/0
creation_time: 1751870573037
experiment_id: '0'
last_update_time: 1751870573037
lifecycle_stage: active
name: Default
